### ISSUE TITLE
There is a regression that no longer allows CNAME record creates

### ISSUE THREAD

**Issue by ngunia** [vinyldns/vinyldns-cli#32]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed.

### Description

[Description of the issue]
See: #16, using 0.8.7 
I haven't pinned the exact commit, but at some point #20 was undone, as this change is not present in the current master.

### Steps to Reproduce

See #16

vinyldns record-set-create --zone-id <zone_id> --record-set-name some-cname --record-set-type CNAME --record-set-ttl 123 --record-set-data test.com

**Expected behavior:** 

Create a CNAME

**Actual behavior:** 

Response code:
400
Response body:
{"errors":["Missing CNAME.cname"]}

**Reproduces how often:** 

100%

### Versions
Tried on 0.8.4, 0.8.7

### Additional Information

I downloaded 0.8.1 and I'm able to create a CNAME. At some point, a regression was introduced.

**Comment by mdb** [comment]
@ngunia Thank you very much for reporting this. I believe this is fixed in `0.8.8`:
https://github.com/vinyldns/vinyldns-cli/releases/tag/v0.8.8

**Comment by mdb** [comment]
I am going to close this issue, as I'm fairly convinced this is fixed in v0.8.8. If I'm wrong, we can re-open the issue.

**Comment by KryptoTrack** [comment]
@mdb I'm on a newer version <v0.9.2> and still seeing this issue.
Response code: 
400
Response body:
{"errors":["Missing CNAME.cname"]}

usage: vinyldns record-set-create --zone-id 903b-d59cc2cb6268 --record-set-name apa-play-test-dns --record-set-type CNAME --record-set-ttl 250 --record-set-data test.net

output:
Request Method:
POST
Request body:
--
Response code: 
400
Response body:
{"errors":["Missing CNAME.cname"]}
